#ifndef H_OPCODE
#define H_OPCODE

enum OpCode {
    OP_ADD, OP_SUB, OP_MULT, OP_DIV, OP_F_ADD, OP_F_SUB, OP_F_MULT, OP_F_DIV, OP_C_ADD, OP_C_SUB, OP_AND, OP_OR,
    OP_EQ, OP_NEQ, OP_B_EQ, OP_B_NEQ, OP_F_EQ, OP_F_NEQ, OP_C_EQ, OP_C_NEQ, OP_LT, OP_LTE, OP_GT, OP_GTE,
    OP_F_LT, OP_F_LTE, OP_F_GT, OP_F_GTE, OP_C_LT, OP_C_LTE, OP_C_GT, OP_C_GTE,
    OP_NEG, OP_F_NEG, OP_NOT, OP_CONCAT, OP_RET, OP_STORE, OP_LOAD,
    OP_PRINT, OP_ALLOC, OP_INDEX, OP_PUSHI,
    OP_STATIC, OP_INITFRAME, OP_ARG, OP_LOCAL, OP_CALL, OP_JMP, OP_JIF, OP_ARGSET
};

enum BaseType {
    TYPE_INT, TYPE_FLOAT, TYPE_BOOL, TYPE_CHAR
};

#endif
