#ifndef H_OPCODE
#define H_OPCODE

enum OpCode {
    OP_ADD, OP_SUB, OP_MULT, OP_DIV, OP_F_ADD, OP_F_SUB, OP_F_MULT, OP_F_DIV, OP_AND, OP_OR, OP_NEG,
    OP_F_NEG, OP_NOT, OP_DEBUG, OP_CONCAT, OP_JMP, OP_JIF, OP_STORE, OP_LOAD, OP_ALLOC, OP_INDEX,
    OP_PUSH, OP_PUSHI, OP_PRINT
};

enum BaseType {
    TYPE_INT, TYPE_FLOAT, TYPE_BOOL, TYPE_CHAR
};

#endif
